# "The Scrapyard" - deckbuilder: scavenge a derelict station. Resources: Physical Damage (fight drones), Money (Credits), Mana (Power).
# Run from project folder: godot -s generate_cards.gd

extends SceneTree

func _init():
	var cards: Array[Dictionary] = [
		{"title": "Rust Knife", "description": "Jury-rigged blade. Better than nothing.", "cost": 0, "pd": 1, "money": 0, "mana": 0},
		{"title": "Pocket Lint", "description": "A few credits stuck in your suit lining.", "cost": 0, "pd": 0, "money": 1, "mana": 0},
		{"title": "Battery Scrap", "description": "Enough juice for one trick.", "cost": 0, "pd": 0, "money": 0, "mana": 1},
		{"title": "Wrench", "description": "Heavy. Good for bolts and skulls.", "cost": 1, "pd": 2, "money": 0, "mana": 0},
		{"title": "Salvage Permit", "description": "Barely legal. Opens some doors.", "cost": 1, "pd": 0, "money": 2, "mana": 0},
		{"title": "Power Cell", "description": "Stolen from a dead drone.", "cost": 1, "pd": 0, "money": 0, "mana": 2},
		{"title": "Stun Baton", "description": "Crackles. Drones hate it.", "cost": 1, "pd": 1, "money": 0, "mana": 1},
		{"title": "Loot Pouch", "description": "Grab and go.", "cost": 1, "pd": 0, "money": 1, "mana": 1},
		{"title": "Brawler", "description": "You learned to throw punches in the ring.", "cost": 1, "pd": 2, "money": 0, "mana": 0},
		{"title": "Side Hustle", "description": "Sell scrap on the way out.", "cost": 1, "pd": 0, "money": 2, "mana": 0},
		{"title": "Plasma Cutter", "description": "Cuts metal. And other things.", "cost": 2, "pd": 3, "money": 0, "mana": 0},
		{"title": "Cred Stick", "description": "Someone left their account open.", "cost": 2, "pd": 0, "money": 3, "mana": 0},
		{"title": "Capacitor", "description": "Stores a surge for your gear.", "cost": 2, "pd": 0, "money": 0, "mana": 3},
		{"title": "Shock Glove", "description": "Up close and personal.", "cost": 2, "pd": 2, "money": 0, "mana": 1},
		{"title": "Scrap Dealer", "description": "You know a guy. He pays well.", "cost": 2, "pd": 0, "money": 2, "mana": 1},
		{"title": "Overcharge", "description": "Push the system. It might push back.", "cost": 2, "pd": 1, "money": 0, "mana": 2},
		{"title": "Crowbar", "description": "Classic. Opens crates and heads.", "cost": 2, "pd": 2, "money": 1, "mana": 0},
		{"title": "Bribe", "description": "Credits smooth the path.", "cost": 2, "pd": 0, "money": 2, "mana": 1},
		{"title": "Welder", "description": "Seal doors or burn through them.", "cost": 2, "pd": 2, "money": 1, "mana": 0},
		{"title": "Backup Cell", "description": "Never run dry.", "cost": 2, "pd": 0, "money": 1, "mana": 2},
		{"title": "Drone Whacker", "description": "Designed for exactly this.", "cost": 3, "pd": 3, "money": 0, "mana": 0},
		{"title": "Black Market", "description": "Sell anything. No questions.", "cost": 3, "pd": 0, "money": 4, "mana": 0},
		{"title": "Reactor Shard", "description": "Dangerous. Powerful.", "cost": 3, "pd": 0, "money": 0, "mana": 4},
		{"title": "Combat Rig", "description": "Armor and attitude.", "cost": 3, "pd": 3, "money": 0, "mana": 1},
		{"title": "Fence", "description": "Moves product fast. Takes a cut.", "cost": 3, "pd": 0, "money": 3, "mana": 1},
		{"title": "Emergency Power", "description": "Bypass safeties. Get juice.", "cost": 3, "pd": 0, "money": 0, "mana": 3},
		{"title": "Heavy Wrench", "description": "One swing. One less drone.", "cost": 3, "pd": 4, "money": 0, "mana": 0},
		{"title": "Pilfer", "description": "Quick fingers. Full pockets.", "cost": 3, "pd": 0, "money": 3, "mana": 0},
		{"title": "Arc Tool", "description": "Tech and teeth.", "cost": 3, "pd": 2, "money": 0, "mana": 2},
		{"title": "Bulk Sale", "description": "Move volume. Get paid.", "cost": 3, "pd": 0, "money": 3, "mana": 1},
		{"title": "Riot Shield", "description": "Advance and strike.", "cost": 3, "pd": 2, "money": 1, "mana": 0},
		{"title": "Barter", "description": "Trade up on the fly.", "cost": 3, "pd": 0, "money": 2, "mana": 2},
		{"title": "Tesla Coil", "description": "Chain lightning in a can.", "cost": 3, "pd": 2, "money": 0, "mana": 2},
		{"title": "Brute", "description": "Sometimes you just hit things.", "cost": 3, "pd": 3, "money": 1, "mana": 0},
		{"title": "Smuggler's Run", "description": "Get in. Get paid. Get out.", "cost": 3, "pd": 0, "money": 3, "mana": 0},
		{"title": "Overclock", "description": "More power. More risk.", "cost": 3, "pd": 0, "money": 0, "mana": 4},
		{"title": "Vibro-Blade", "description": "Cuts through armor like butter.", "cost": 4, "pd": 4, "money": 0, "mana": 0},
		{"title": "Vault Codes", "description": "Worth every credit you paid.", "cost": 4, "pd": 0, "money": 5, "mana": 0},
		{"title": "Fusion Cell", "description": "Military grade. Stolen grade.", "cost": 4, "pd": 0, "money": 0, "mana": 5},
		{"title": "Enforcer", "description": "Hit hard. Hit twice.", "cost": 4, "pd": 4, "money": 0, "mana": 1},
		{"title": "Auction", "description": "Sell to the highest bidder.", "cost": 4, "pd": 0, "money": 4, "mana": 1},
		{"title": "Surge Pack", "description": "Instant power. No questions.", "cost": 4, "pd": 0, "money": 0, "mana": 4},
		{"title": "Breach Hammer", "description": "For when locks won't do.", "cost": 4, "pd": 4, "money": 0, "mana": 0},
		{"title": "Payoff", "description": "Everyone has a price.", "cost": 4, "pd": 0, "money": 4, "mana": 0},
		{"title": "Plasma Core", "description": "Runs hot. Runs strong.", "cost": 4, "pd": 0, "money": 0, "mana": 4},
		{"title": "Shock and Awe", "description": "Stun. Strike. Loot.", "cost": 4, "pd": 3, "money": 0, "mana": 2},
		{"title": "Broker", "description": "Connections pay.", "cost": 4, "pd": 0, "money": 3, "mana": 2},
		{"title": "EMP Knuckle", "description": "Short range. Big spark.", "cost": 4, "pd": 3, "money": 0, "mana": 2},
		{"title": "Scrap Baron", "description": "You own the yard.", "cost": 4, "pd": 0, "money": 4, "mana": 1},
		{"title": "Rigged Generator", "description": "Steal power. Leave a mess.", "cost": 4, "pd": 1, "money": 0, "mana": 4},
		{"title": "Mercenary", "description": "Hired muscle. Worth it.", "cost": 4, "pd": 3, "money": 1, "mana": 0},
		{"title": "Side Deal", "description": "Cut out the middleman.", "cost": 4, "pd": 0, "money": 3, "mana": 2},
		{"title": "Arc Welder", "description": "Build or break.", "cost": 4, "pd": 3, "money": 1, "mana": 1},
		{"title": "Bulk Buyer", "description": "They take it all. You take the credits.", "cost": 4, "pd": 0, "money": 4, "mana": 0},
		{"title": "Reactor Tap", "description": "Dangerous. Effective.", "cost": 4, "pd": 0, "money": 0, "mana": 5},
		{"title": "Monofilament Saw", "description": "Cuts anything. Everything.", "cost": 5, "pd": 5, "money": 0, "mana": 0},
		{"title": "Treasure Map", "description": "X marks the payday.", "cost": 5, "pd": 0, "money": 6, "mana": 0},
		{"title": "Core Shard", "description": "Pure energy. Handle with care.", "cost": 5, "pd": 0, "money": 0, "mana": 6},
		{"title": "Warmaster", "description": "Born for the scrap.", "cost": 5, "pd": 5, "money": 0, "mana": 1},
		{"title": "Kingpin", "description": "The yard answers to you.", "cost": 5, "pd": 0, "money": 5, "mana": 1},
		{"title": "Overdrive", "description": "Push past the red line.", "cost": 5, "pd": 0, "money": 0, "mana": 5},
		{"title": "Siege Breaker", "description": "Nothing stays closed.", "cost": 5, "pd": 5, "money": 0, "mana": 0},
		{"title": "Vault Heist", "description": "The big score.", "cost": 5, "pd": 0, "money": 5, "mana": 0},
		{"title": "Singularity Cell", "description": "Power from the edge.", "cost": 5, "pd": 0, "money": 0, "mana": 5},
		{"title": "Champion", "description": "Fight. Win. Get paid.", "cost": 5, "pd": 4, "money": 1, "mana": 1},
		{"title": "Cartel Contact", "description": "They pay top credit.", "cost": 5, "pd": 0, "money": 4, "mana": 2},
		{"title": "Storm Core", "description": "Lightning in your pocket.", "cost": 5, "pd": 0, "money": 0, "mana": 5},
		{"title": "Berserker", "description": "Rage pays in scrap.", "cost": 5, "pd": 4, "money": 1, "mana": 0},
		{"title": "Insider", "description": "Best prices. No paper trail.", "cost": 5, "pd": 0, "money": 4, "mana": 1},
		{"title": "Volt Fist", "description": "Punch with power.", "cost": 5, "pd": 3, "money": 0, "mana": 3},
		{"title": "Junk Baron", "description": "Your pile. Your rules.", "cost": 5, "pd": 1, "money": 4, "mana": 1},
		{"title": "Reactor Raid", "description": "Take what you need.", "cost": 5, "pd": 0, "money": 1, "mana": 5},
		{"title": "Scrap Cannon", "description": "Improvised. Lethal.", "cost": 5, "pd": 4, "money": 0, "mana": 2},
		{"title": "Bounty", "description": "Someone wanted. You delivered.", "cost": 5, "pd": 0, "money": 4, "mana": 2},
		{"title": "Surge Rifle", "description": "Stun from a distance.", "cost": 5, "pd": 3, "money": 0, "mana": 3},
		{"title": "Fixer", "description": "Makes problems disappear. For a fee.", "cost": 5, "pd": 0, "money": 5, "mana": 0},
		{"title": "Plasma Fist", "description": "Close-range devastation.", "cost": 5, "pd": 4, "money": 0, "mana": 2},
		{"title": "Smuggler", "description": "In and out. Rich.", "cost": 5, "pd": 0, "money": 4, "mana": 1},
		{"title": "Arc Reactor", "description": "Heart of the station. In your pack.", "cost": 5, "pd": 0, "money": 0, "mana": 5},
		{"title": "Bunker Buster", "description": "For the stubborn doors.", "cost": 5, "pd": 5, "money": 0, "mana": 0},
		{"title": "Loot Run", "description": "One more crate. One more credit.", "cost": 5, "pd": 0, "money": 5, "mana": 0},
		{"title": "Emergency Core", "description": "Last resort. Full power.", "cost": 5, "pd": 0, "money": 0, "mana": 5},
		{"title": "Brawler's Cut", "description": "You cleared the way. Take your share.", "cost": 2, "pd": 2, "money": 1, "mana": 0},
		{"title": "Scrounge", "description": "Find value in the junk.", "cost": 2, "pd": 0, "money": 2, "mana": 0},
		{"title": "Siphon", "description": "Drain a line. Fill your cell.", "cost": 2, "pd": 0, "money": 0, "mana": 2},
		{"title": "Gut Punch", "description": "No finesse. Just results.", "cost": 2, "pd": 2, "money": 0, "mana": 0},
		{"title": "Tip-Off", "description": "A lead. A payout.", "cost": 2, "pd": 0, "money": 2, "mana": 0},
		{"title": "Jury-Rig", "description": "Make it work. Once.", "cost": 2, "pd": 0, "money": 0, "mana": 2},
		{"title": "Knuckleduster", "description": "Old school. Still works.", "cost": 2, "pd": 2, "money": 0, "mana": 0},
		{"title": "Haggle", "description": "Every credit counts.", "cost": 2, "pd": 0, "money": 2, "mana": 0},
		{"title": "Hotwire", "description": "Bypass. Extract. Go.", "cost": 2, "pd": 0, "money": 0, "mana": 2},
		{"title": "Pipe", "description": "Heavy pipe. Heavy swing.", "cost": 2, "pd": 2, "money": 0, "mana": 0},
		{"title": "Finder's Fee", "description": "You found it. You keep some.", "cost": 2, "pd": 0, "money": 2, "mana": 0},
		{"title": "Spare Parts", "description": "Cobble together some power.", "cost": 2, "pd": 0, "money": 0, "mana": 2},
		{"title": "Sweep", "description": "Clear the room. Take the loot.", "cost": 2, "pd": 1, "money": 1, "mana": 0},
		{"title": "Kickback", "description": "They owe you.", "cost": 2, "pd": 0, "money": 1, "mana": 1},
		{"title": "Short Circuit", "description": "Redirect power. Your way.", "cost": 2, "pd": 1, "money": 0, "mana": 1},
		{"title": "Bunker Brawl", "description": "Close quarters. No mercy.", "cost": 4, "pd": 3, "money": 1, "mana": 0},
		{"title": "Trade Route", "description": "Steady credits. Steady risk.", "cost": 4, "pd": 0, "money": 3, "mana": 1},
		{"title": "Power Theft", "description": "They won't miss it.", "cost": 4, "pd": 0, "money": 1, "mana": 3},
		{"title": "Heavy Metal", "description": "Swing. Connect. Repeat.", "cost": 4, "pd": 3, "money": 1, "mana": 0},
		{"title": "Auction Block", "description": "Sell to the desperate.", "cost": 4, "pd": 0, "money": 4, "mana": 0},
		{"title": "Drain", "description": "Suck the station dry.", "cost": 4, "pd": 0, "money": 0, "mana": 4},
		{"title": "Rust and Fury", "description": "Age and anger.", "cost": 4, "pd": 4, "money": 0, "mana": 0},
		{"title": "Sweet Deal", "description": "Too good to pass up.", "cost": 4, "pd": 0, "money": 4, "mana": 0},
		{"title": "Backup Reactor", "description": "When one isn't enough.", "cost": 4, "pd": 0, "money": 0, "mana": 4},
		{"title": "Clean Sweep", "description": "Clear. Loot. Leave.", "cost": 4, "pd": 2, "money": 2, "mana": 0},
		{"title": "Double Deal", "description": "Two buyers. One seller.", "cost": 4, "pd": 0, "money": 3, "mana": 1},
		{"title": "Chain Lightning", "description": "One zap. Many targets.", "cost": 4, "pd": 2, "money": 0, "mana": 2},
		{"title": "Veteran", "description": "Seen it all. Broke it all.", "cost": 4, "pd": 3, "money": 1, "mana": 0},
		{"title": "Cash Flow", "description": "Credits find a way.", "cost": 4, "pd": 0, "money": 3, "mana": 1},
		{"title": "Overload", "description": "More than it can take.", "cost": 4, "pd": 0, "money": 0, "mana": 4},
		{"title": "Last Stand", "description": "Nothing left to lose.", "cost": 5, "pd": 4, "money": 1, "mana": 0},
		{"title": "Fortune", "description": "Luck favors the bold.", "cost": 5, "pd": 0, "money": 4, "mana": 1},
		{"title": "Final Surge", "description": "All or nothing.", "cost": 5, "pd": 0, "money": 0, "mana": 4},
		{"title": "Titan", "description": "Unstoppable. Unpaid. For now.", "cost": 5, "pd": 4, "money": 1, "mana": 1},
		{"title": "Tycoon", "description": "The yard runs on your credit.", "cost": 5, "pd": 0, "money": 4, "mana": 2},
		{"title": "Storm Caller", "description": "Bring the lightning.", "cost": 5, "pd": 0, "money": 1, "mana": 4},
		{"title": "Warlord", "description": "Conquer. Collect. Cash out.", "cost": 5, "pd": 4, "money": 2, "mana": 0},
		{"title": "Magnate", "description": "Every deal goes through you.", "cost": 5, "pd": 0, "money": 5, "mana": 0},
		{"title": "Architect", "description": "You build the power grid.", "cost": 5, "pd": 0, "money": 0, "mana": 5},
		{"title": "Triple Threat", "description": "Fight. Trade. Power up.", "cost": 5, "pd": 2, "money": 2, "mana": 2},
	]
	var dir := DirAccess.open("res://")
	if not dir.dir_exists("cards"):
		dir.make_dir("cards")
	for i in cards.size():
		var c: Dictionary = cards[i]
		var card := CardData.new()
		card.title = c.title
		card.description = c.description
		card.cost = c.cost
		card.physical_damage_gen = c.pd
		card.money_gen = c.money
		card.mana_gen = c.mana
		var path := "res://cards/card_%03d.tres" % (i + 1)
		var err := ResourceSaver.save(card, path)
		if err != OK:
			print("Failed to save ", path, " error: ", err)
		else:
			print("Saved ", path)
	print("Done. Generated ", cards.size(), " cards.")
	quit()
